const pallete = {
  algaegreen: '#26c165',
  darkgreen: '#0A9830',
  white: '#FFFFFF',
  dark: '#131a22',
  darkgrey: '#b7b7b7',
  mediumgrey: '#FAFAFA',
  lightgrey: '#F7F9F8',
  blackgrey: '#909090',
  red: '#CC0000',
  blue: '#0052CC',
  black2: 'rgba(0, 0, 0, 0.3)',
  black3: 'rgba(0, 0, 0, 0.8)',
  black: '#000000',
  carrot: '#FC9443',
  sunflower: '#EFB916',
};
export const colors = {
  primary: pallete.algaegreen,
  secondary: pallete.dark,
  lightgrey: pallete.lightgrey,
  darkgrey: pallete.darkgrey,
  orange: pallete.carrot,
  yellow: pallete.sunflower,
  darkgreen: pallete.darkgreen,
  white: pallete.white,
  mediumgrey: pallete.mediumgrey,
  red: pallete.red,
  loadingbackground2: pallete.black3,
  loadingbackground: pallete.black2,
  black: pallete.black,
  text: {
    black: pallete.dark,
    green: pallete.algaegreen,
    lightgrey: pallete.lightgrey,
    white: pallete.white,
    darkgrey: pallete.blackgrey,
    red: pallete.red,
  },
  button: {
    green: pallete.algaegreen,
    lightgrey: pallete.lightgrey,
    white: pallete.white,
    darkgrey: pallete.darkgrey,
    red: pallete.red,
  },
  border: {
    background: pallete.darkgrey,
    grey: pallete.darkgrey,
    mediumgrey: pallete.mediumgrey,
    lightgrey: pallete.lightgrey,
    red: pallete.red,
    blue: pallete.blue,
  },
};
